on:
  workflow_dispatch:
  push: 

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: Get CASL Library Version
    steps:
      - name: Get version from project file
        id: get-version
        uses: KinsonDigital/vget@v0.2
        with:
          repo-owner-and-name: 'KinsonDigital/CASL'
          relative-file-path: 'CASL\CASL.csproj'
          user-name: 'kinsondigital@gmail.com'
          password: ${{ secrets.REPO_PASSWORD }}
      # Use the output from the `get-version` step
      - name: Display Library Version
        run: echo "The project file version is ${{ steps.get-version.outputs.version }}"
