on:
  workflow_dispatch:
  push: 

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: Get Project File Version
    steps:
      - name: Get version from project file
        id: get-version
        uses: KinsonDigital/vget@v0.3.0
        with:
          repo-owner-and-name: 'CalvinWilkinson/vget-testing'
          branch: 'master'
          relative-file-path: 'src\TestProjectFile.csproj'
          user-name: 'kinsondigital@gmail.com'
          password: ${{ secrets.REPO_PASSWORD }}
          contains: '.2.'
      # Use the output from the `get-version` step
      - name: Display Library Version
        run: echo "The project file version is ${{ steps.get-version.outputs.version }}"
