on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - name: Get version from project file
        id: get-version
        uses: KinsonDigital/vget@v0.2
        with:
          repo-owner: 'KinsonDigital'
          repo-name: 'vget-testing'
          relative-file-path: 'CASL\CASL.csproj'
          user-name: 'kinsondigital@gmail.com'
          password: ${{ secrets.REPO_PASSWORD }}
      # Use the output from the `get-version` step
      - name: Get the output time
        run: echo "The project file version is ${{ steps.get-version.outputs.version }}"